icons_format = "{icon}"

[theme]
theme = "plain"
[theme.overrides]
good_fg = "#27ae60"
good_bg = "#20242c"
warning_fg = "#f39c12"
warning_bg = "#20242c"
critical_fg = "#e74c3c"
critical_bg = "#20242c"
info_fg = "#27ae60"
info_bg = "#20242c"
separator = ""
separator_bg = "#20242c"
separator_fg = "#4c7899"
idle_fg = "#ffffff"
idle_bg = "#20242c"

[icons]
# icons = "awesome4"
icons = "material-nf"

[[block]]
block = "music"
player = "spotify"
format = "   {$combo.str(max_w:100)  $prev $play $next} "
[[block.click]]
button = "left"
action = "play_pause"

[[block]]
block = "cpu"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
