# Basic Configuration
backend = "glx";
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
vsync = true;

# Opacity
opacity-rule = [
    "90:class_g = 'URxvt'"
];

# Shadow
shadow = false;
no-dock-shadow = true;
no-dnd-shadow = true;
clear-shadow = true;
shadow-radius = 7;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-opacity = 0.7;
shadow-exclude = [
    "! name~=''",
    "name = 'Notification'",
    "name = 'Plank'",
    "name = 'Docky'",
    "name = 'Kupfer'",
    "name = 'xfce4-notifyd'",
    "name = 'notify-osd'",
    "name *= 'VLC'",
    "name *= 'compton'",
    "name *= 'picom'",
    "class_g = 'Conky'",
    "class_g = 'Cairo-clock'",
    "_GTK_FRAME_EXTENTS@:c"
];

# Fading
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 4;

# Other
# detect-rounded-corners = true;
corner-radius = 10
round-borders = 1

rounded-corners-exclude = [
  "window_type = 'dock'",
  "class_g = 'i3-frame'"
];
